// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class npr_update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(npr_update1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305062109199_npr_update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
