// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EventCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201305071506152_EventCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
