// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nprslot_printbadge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nprslot_printbadge));
        
        string IMigrationMetadata.Id
        {
            get { return "201305172149005_nprslot_printbadge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
