// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ticket_no : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticket_no));
        
        string IMigrationMetadata.Id
        {
            get { return "201305081687382_ticket_no"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
