// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

	public sealed partial class resevent_paid_tickets : IMigrationMetadata
    {
		private readonly ResourceManager Resources = new ResourceManager(typeof(resevent_paid_tickets));
        
        string IMigrationMetadata.Id
        {
			get { return "201311051056031_resevent_paid_tickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
