// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SpeakerEvents : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpeakerEvents));
        
        string IMigrationMetadata.Id
        {
            get { return "201306191748067_SpeakerEvents"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
