// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class giveaway : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(giveaway));
        
        string IMigrationMetadata.Id
        {
            get { return "201306010406034_giveaway"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
