// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class store_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201305080133167_store_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
