// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class slot_notes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slot_notes));
        
        string IMigrationMetadata.Id
        {
            get { return "201305220624479_slot_notes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
