// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class npr_slot_guide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(npr_slot_guide));
        
        string IMigrationMetadata.Id
        {
            get { return "201305142359591_npr_slot_guide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
