// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class optional_stores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(optional_stores));
        
        string IMigrationMetadata.Id
        {
            get { return "201304032322416_optional_stores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
