// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class slot_no_longer_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slot_no_longer_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201305071838534_slot_no_longer_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
