// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

	public sealed partial class tickets_authorization : IMigrationMetadata
    {
		private readonly ResourceManager Resources = new ResourceManager(typeof(tickets_authorization));
        
        string IMigrationMetadata.Id
        {
			get { return "201311051316031_tickets_authorization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
