// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class media_owner_id_event_visibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(media_owner_id_event_visibility));
        
        string IMigrationMetadata.Id
        {
            get { return "201305081631500_media_owner_id_event_visibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
