// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class transactions1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transactions1));
        
        string IMigrationMetadata.Id
        {
            get { return "201305281709337_transactions1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
