// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class relation_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relation_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201304071842238_relation_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
