// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

	public sealed partial class tickets_additional_info : IMigrationMetadata
    {
		private readonly ResourceManager Resources = new ResourceManager(typeof(tickets_additional_info));
        
        string IMigrationMetadata.Id
        {
			get { return "201311141316032_tickets_additional_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
