// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EventCompilation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventCompilation));
        
        string IMigrationMetadata.Id
        {
            get { return "201305071525056_EventCompilation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
