// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class event_media : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(event_media));
        
        string IMigrationMetadata.Id
        {
            get { return "201305102024327_event_media"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
