// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ticket_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticket_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201305201614151_ticket_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
