// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class minimum_daily_capacity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(minimum_daily_capacity));
        
        string IMigrationMetadata.Id
        {
            get { return "201308161935319_minimum_daily_capacity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
