// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ticketguest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketguest));
        
        string IMigrationMetadata.Id
        {
            get { return "201411041005471_ticketguest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
