// <auto-generated />
namespace npr.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ticketguest1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketguest1));
        
        string IMigrationMetadata.Id
        {
            get { return "201411041354003_ticketguest1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
