//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace cfacome.entity.dao.Designer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CfaComStoriesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CfaComStoriesEntities object using the connection string found in the 'CfaComStoriesEntities' section of the application configuration file.
        /// </summary>
        public CfaComStoriesEntities() : base("name=CfaComStoriesEntities", "CfaComStoriesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CfaComStoriesEntities object.
        /// </summary>
        public CfaComStoriesEntities(string connectionString) : base(connectionString, "CfaComStoriesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CfaComStoriesEntities object.
        /// </summary>
        public CfaComStoriesEntities(EntityConnection connection) : base(connection, "CfaComStoriesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V2StoryImageAuthorWithTagRating> V2StoryImageAuthorWithTagRating
        {
            get
            {
                if ((_V2StoryImageAuthorWithTagRating == null))
                {
                    _V2StoryImageAuthorWithTagRating = base.CreateObjectSet<V2StoryImageAuthorWithTagRating>("V2StoryImageAuthorWithTagRating");
                }
                return _V2StoryImageAuthorWithTagRating;
            }
        }
        private ObjectSet<V2StoryImageAuthorWithTagRating> _V2StoryImageAuthorWithTagRating;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V2StoryRatingSummary> V2StoryRatingSummary
        {
            get
            {
                if ((_V2StoryRatingSummary == null))
                {
                    _V2StoryRatingSummary = base.CreateObjectSet<V2StoryRatingSummary>("V2StoryRatingSummary");
                }
                return _V2StoryRatingSummary;
            }
        }
        private ObjectSet<V2StoryRatingSummary> _V2StoryRatingSummary;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V2StoryTagSummary> V2StoryTagSummary
        {
            get
            {
                if ((_V2StoryTagSummary == null))
                {
                    _V2StoryTagSummary = base.CreateObjectSet<V2StoryTagSummary>("V2StoryTagSummary");
                }
                return _V2StoryTagSummary;
            }
        }
        private ObjectSet<V2StoryTagSummary> _V2StoryTagSummary;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<V2StoryWithImageAuthor> V2StoryWithImageAuthor
        {
            get
            {
                if ((_V2StoryWithImageAuthor == null))
                {
                    _V2StoryWithImageAuthor = base.CreateObjectSet<V2StoryWithImageAuthor>("V2StoryWithImageAuthor");
                }
                return _V2StoryWithImageAuthor;
            }
        }
        private ObjectSet<V2StoryWithImageAuthor> _V2StoryWithImageAuthor;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V2StoryImageAuthorWithTagRating EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV2StoryImageAuthorWithTagRating(V2StoryImageAuthorWithTagRating v2StoryImageAuthorWithTagRating)
        {
            base.AddObject("V2StoryImageAuthorWithTagRating", v2StoryImageAuthorWithTagRating);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V2StoryRatingSummary EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV2StoryRatingSummary(V2StoryRatingSummary v2StoryRatingSummary)
        {
            base.AddObject("V2StoryRatingSummary", v2StoryRatingSummary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V2StoryTagSummary EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV2StoryTagSummary(V2StoryTagSummary v2StoryTagSummary)
        {
            base.AddObject("V2StoryTagSummary", v2StoryTagSummary);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the V2StoryWithImageAuthor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToV2StoryWithImageAuthor(V2StoryWithImageAuthor v2StoryWithImageAuthor)
        {
            base.AddObject("V2StoryWithImageAuthor", v2StoryWithImageAuthor);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoriesEntityModel", Name="V2StoryImageAuthorWithTagRating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V2StoryImageAuthorWithTagRating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V2StoryImageAuthorWithTagRating object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="storyContent">Initial value of the StoryContent property.</param>
        /// <param name="authorID">Initial value of the AuthorID property.</param>
        /// <param name="imageID">Initial value of the ImageID property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        /// <param name="storyVersion">Initial value of the StoryVersion property.</param>
        /// <param name="editorID">Initial value of the EditorID property.</param>
        /// <param name="reviewApproval">Initial value of the ReviewApproval property.</param>
        /// <param name="finalApproval">Initial value of the FinalApproval property.</param>
        /// <param name="reviewUnsure">Initial value of the ReviewUnsure property.</param>
        /// <param name="isUnusableNegative">Initial value of the IsUnusableNegative property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="owner">Initial value of the Owner property.</param>
        /// <param name="poster">Initial value of the Poster property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="mdWidth">Initial value of the MdWidth property.</param>
        /// <param name="mdHeight">Initial value of the MdHeight property.</param>
        /// <param name="lgWidth">Initial value of the LgWidth property.</param>
        /// <param name="lgHeight">Initial value of the LgHeight property.</param>
        /// <param name="promoWidth">Initial value of the PromoWidth property.</param>
        /// <param name="promoHeight">Initial value of the PromoHeight property.</param>
        public static V2StoryImageAuthorWithTagRating CreateV2StoryImageAuthorWithTagRating(global::System.Decimal id, global::System.String title, global::System.String storyContent, global::System.Decimal authorID, global::System.Decimal imageID, global::System.DateTime postingDate, global::System.Int32 storyVersion, global::System.Int32 editorID, global::System.Boolean reviewApproval, global::System.Boolean finalApproval, global::System.Boolean reviewUnsure, global::System.Boolean isUnusableNegative, global::System.String fileName, global::System.String owner, global::System.Decimal poster, global::System.Decimal width, global::System.Decimal height, global::System.Decimal mdWidth, global::System.Decimal mdHeight, global::System.Decimal lgWidth, global::System.Decimal lgHeight, global::System.Decimal promoWidth, global::System.Decimal promoHeight)
        {
            V2StoryImageAuthorWithTagRating v2StoryImageAuthorWithTagRating = new V2StoryImageAuthorWithTagRating();
            v2StoryImageAuthorWithTagRating.ID = id;
            v2StoryImageAuthorWithTagRating.Title = title;
            v2StoryImageAuthorWithTagRating.StoryContent = storyContent;
            v2StoryImageAuthorWithTagRating.AuthorID = authorID;
            v2StoryImageAuthorWithTagRating.ImageID = imageID;
            v2StoryImageAuthorWithTagRating.PostingDate = postingDate;
            v2StoryImageAuthorWithTagRating.StoryVersion = storyVersion;
            v2StoryImageAuthorWithTagRating.EditorID = editorID;
            v2StoryImageAuthorWithTagRating.ReviewApproval = reviewApproval;
            v2StoryImageAuthorWithTagRating.FinalApproval = finalApproval;
            v2StoryImageAuthorWithTagRating.ReviewUnsure = reviewUnsure;
            v2StoryImageAuthorWithTagRating.IsUnusableNegative = isUnusableNegative;
            v2StoryImageAuthorWithTagRating.FileName = fileName;
            v2StoryImageAuthorWithTagRating.Owner = owner;
            v2StoryImageAuthorWithTagRating.Poster = poster;
            v2StoryImageAuthorWithTagRating.Width = width;
            v2StoryImageAuthorWithTagRating.Height = height;
            v2StoryImageAuthorWithTagRating.MdWidth = mdWidth;
            v2StoryImageAuthorWithTagRating.MdHeight = mdHeight;
            v2StoryImageAuthorWithTagRating.LgWidth = lgWidth;
            v2StoryImageAuthorWithTagRating.LgHeight = lgHeight;
            v2StoryImageAuthorWithTagRating.PromoWidth = promoWidth;
            v2StoryImageAuthorWithTagRating.PromoHeight = promoHeight;
            return v2StoryImageAuthorWithTagRating;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoryContent
        {
            get
            {
                return _StoryContent;
            }
            set
            {
                OnStoryContentChanging(value);
                ReportPropertyChanging("StoryContent");
                _StoryContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoryContent");
                OnStoryContentChanged();
            }
        }
        private global::System.String _StoryContent;
        partial void OnStoryContentChanging(global::System.String value);
        partial void OnStoryContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AuthorID
        {
            get
            {
                return _AuthorID;
            }
            set
            {
                OnAuthorIDChanging(value);
                ReportPropertyChanging("AuthorID");
                _AuthorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorID");
                OnAuthorIDChanged();
            }
        }
        private global::System.Decimal _AuthorID;
        partial void OnAuthorIDChanging(global::System.Decimal value);
        partial void OnAuthorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ImageID
        {
            get
            {
                return _ImageID;
            }
            set
            {
                OnImageIDChanging(value);
                ReportPropertyChanging("ImageID");
                _ImageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageID");
                OnImageIDChanged();
            }
        }
        private global::System.Decimal _ImageID;
        partial void OnImageIDChanging(global::System.Decimal value);
        partial void OnImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                OnPostingDateChanging(value);
                ReportPropertyChanging("PostingDate");
                _PostingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostingDate");
                OnPostingDateChanged();
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentEntryID
        {
            get
            {
                return _CurrentEntryID;
            }
            set
            {
                OnCurrentEntryIDChanging(value);
                ReportPropertyChanging("CurrentEntryID");
                _CurrentEntryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentEntryID");
                OnCurrentEntryIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentEntryID;
        partial void OnCurrentEntryIDChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentEntryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoryVersion
        {
            get
            {
                return _StoryVersion;
            }
            set
            {
                OnStoryVersionChanging(value);
                ReportPropertyChanging("StoryVersion");
                _StoryVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoryVersion");
                OnStoryVersionChanged();
            }
        }
        private global::System.Int32 _StoryVersion;
        partial void OnStoryVersionChanging(global::System.Int32 value);
        partial void OnStoryVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EditorID
        {
            get
            {
                return _EditorID;
            }
            set
            {
                OnEditorIDChanging(value);
                ReportPropertyChanging("EditorID");
                _EditorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditorID");
                OnEditorIDChanged();
            }
        }
        private global::System.Int32 _EditorID;
        partial void OnEditorIDChanging(global::System.Int32 value);
        partial void OnEditorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ReviewApproval
        {
            get
            {
                return _ReviewApproval;
            }
            set
            {
                OnReviewApprovalChanging(value);
                ReportPropertyChanging("ReviewApproval");
                _ReviewApproval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReviewApproval");
                OnReviewApprovalChanged();
            }
        }
        private global::System.Boolean _ReviewApproval;
        partial void OnReviewApprovalChanging(global::System.Boolean value);
        partial void OnReviewApprovalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FinalApproval
        {
            get
            {
                return _FinalApproval;
            }
            set
            {
                OnFinalApprovalChanging(value);
                ReportPropertyChanging("FinalApproval");
                _FinalApproval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalApproval");
                OnFinalApprovalChanged();
            }
        }
        private global::System.Boolean _FinalApproval;
        partial void OnFinalApprovalChanging(global::System.Boolean value);
        partial void OnFinalApprovalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Reviewed
        {
            get
            {
                return _Reviewed;
            }
            set
            {
                OnReviewedChanging(value);
                ReportPropertyChanging("Reviewed");
                _Reviewed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reviewed");
                OnReviewedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Reviewed;
        partial void OnReviewedChanging(Nullable<global::System.Boolean> value);
        partial void OnReviewedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Views
        {
            get
            {
                return _Views;
            }
            set
            {
                OnViewsChanging(value);
                ReportPropertyChanging("Views");
                _Views = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Views");
                OnViewsChanged();
            }
        }
        private Nullable<global::System.Decimal> _Views;
        partial void OnViewsChanging(Nullable<global::System.Decimal> value);
        partial void OnViewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CategoryID;
        partial void OnCategoryIDChanging(Nullable<global::System.Decimal> value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDraft
        {
            get
            {
                return _IsDraft;
            }
            set
            {
                OnIsDraftChanging(value);
                ReportPropertyChanging("IsDraft");
                _IsDraft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDraft");
                OnIsDraftChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDraft;
        partial void OnIsDraftChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDraftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsUnusable
        {
            get
            {
                return _IsUnusable;
            }
            set
            {
                OnIsUnusableChanging(value);
                ReportPropertyChanging("IsUnusable");
                _IsUnusable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUnusable");
                OnIsUnusableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsUnusable;
        partial void OnIsUnusableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsUnusableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ReviewUnsure
        {
            get
            {
                return _ReviewUnsure;
            }
            set
            {
                OnReviewUnsureChanging(value);
                ReportPropertyChanging("ReviewUnsure");
                _ReviewUnsure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReviewUnsure");
                OnReviewUnsureChanged();
            }
        }
        private global::System.Boolean _ReviewUnsure;
        partial void OnReviewUnsureChanging(global::System.Boolean value);
        partial void OnReviewUnsureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUnusableNegative
        {
            get
            {
                return _IsUnusableNegative;
            }
            set
            {
                OnIsUnusableNegativeChanging(value);
                ReportPropertyChanging("IsUnusableNegative");
                _IsUnusableNegative = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUnusableNegative");
                OnIsUnusableNegativeChanged();
            }
        }
        private global::System.Boolean _IsUnusableNegative;
        partial void OnIsUnusableNegativeChanging(global::System.Boolean value);
        partial void OnIsUnusableNegativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.String _Owner;
        partial void OnOwnerChanging(global::System.String value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Poster
        {
            get
            {
                return _Poster;
            }
            set
            {
                OnPosterChanging(value);
                ReportPropertyChanging("Poster");
                _Poster = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Poster");
                OnPosterChanged();
            }
        }
        private global::System.Decimal _Poster;
        partial void OnPosterChanging(global::System.Decimal value);
        partial void OnPosterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Decimal _Width;
        partial void OnWidthChanging(global::System.Decimal value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Decimal _Height;
        partial void OnHeightChanging(global::System.Decimal value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MdWidth
        {
            get
            {
                return _MdWidth;
            }
            set
            {
                OnMdWidthChanging(value);
                ReportPropertyChanging("MdWidth");
                _MdWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MdWidth");
                OnMdWidthChanged();
            }
        }
        private global::System.Decimal _MdWidth;
        partial void OnMdWidthChanging(global::System.Decimal value);
        partial void OnMdWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MdHeight
        {
            get
            {
                return _MdHeight;
            }
            set
            {
                OnMdHeightChanging(value);
                ReportPropertyChanging("MdHeight");
                _MdHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MdHeight");
                OnMdHeightChanged();
            }
        }
        private global::System.Decimal _MdHeight;
        partial void OnMdHeightChanging(global::System.Decimal value);
        partial void OnMdHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LgWidth
        {
            get
            {
                return _LgWidth;
            }
            set
            {
                OnLgWidthChanging(value);
                ReportPropertyChanging("LgWidth");
                _LgWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LgWidth");
                OnLgWidthChanged();
            }
        }
        private global::System.Decimal _LgWidth;
        partial void OnLgWidthChanging(global::System.Decimal value);
        partial void OnLgWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LgHeight
        {
            get
            {
                return _LgHeight;
            }
            set
            {
                OnLgHeightChanging(value);
                ReportPropertyChanging("LgHeight");
                _LgHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LgHeight");
                OnLgHeightChanged();
            }
        }
        private global::System.Decimal _LgHeight;
        partial void OnLgHeightChanging(global::System.Decimal value);
        partial void OnLgHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromoWidth
        {
            get
            {
                return _PromoWidth;
            }
            set
            {
                OnPromoWidthChanging(value);
                ReportPropertyChanging("PromoWidth");
                _PromoWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromoWidth");
                OnPromoWidthChanged();
            }
        }
        private global::System.Decimal _PromoWidth;
        partial void OnPromoWidthChanging(global::System.Decimal value);
        partial void OnPromoWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromoHeight
        {
            get
            {
                return _PromoHeight;
            }
            set
            {
                OnPromoHeightChanging(value);
                ReportPropertyChanging("PromoHeight");
                _PromoHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromoHeight");
                OnPromoHeightChanged();
            }
        }
        private global::System.Decimal _PromoHeight;
        partial void OnPromoHeightChanging(global::System.Decimal value);
        partial void OnPromoHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StoryRating
        {
            get
            {
                return _StoryRating;
            }
            set
            {
                OnStoryRatingChanging(value);
                ReportPropertyChanging("StoryRating");
                _StoryRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoryRating");
                OnStoryRatingChanged();
            }
        }
        private Nullable<global::System.Decimal> _StoryRating;
        partial void OnStoryRatingChanging(Nullable<global::System.Decimal> value);
        partial void OnStoryRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberOfRatings
        {
            get
            {
                return _NumberOfRatings;
            }
            set
            {
                OnNumberOfRatingsChanging(value);
                ReportPropertyChanging("NumberOfRatings");
                _NumberOfRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfRatings");
                OnNumberOfRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberOfRatings;
        partial void OnNumberOfRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnNumberOfRatingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TagDescription
        {
            get
            {
                return _TagDescription;
            }
            set
            {
                OnTagDescriptionChanging(value);
                ReportPropertyChanging("TagDescription");
                _TagDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TagDescription");
                OnTagDescriptionChanged();
            }
        }
        private global::System.String _TagDescription;
        partial void OnTagDescriptionChanging(global::System.String value);
        partial void OnTagDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoriesEntityModel", Name="V2StoryRatingSummary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V2StoryRatingSummary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V2StoryRatingSummary object.
        /// </summary>
        /// <param name="storyID">Initial value of the StoryID property.</param>
        public static V2StoryRatingSummary CreateV2StoryRatingSummary(global::System.Decimal storyID)
        {
            V2StoryRatingSummary v2StoryRatingSummary = new V2StoryRatingSummary();
            v2StoryRatingSummary.StoryID = storyID;
            return v2StoryRatingSummary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal StoryID
        {
            get
            {
                return _StoryID;
            }
            set
            {
                if (_StoryID != value)
                {
                    OnStoryIDChanging(value);
                    ReportPropertyChanging("StoryID");
                    _StoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StoryID");
                    OnStoryIDChanged();
                }
            }
        }
        private global::System.Decimal _StoryID;
        partial void OnStoryIDChanging(global::System.Decimal value);
        partial void OnStoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StoryRating
        {
            get
            {
                return _StoryRating;
            }
            set
            {
                OnStoryRatingChanging(value);
                ReportPropertyChanging("StoryRating");
                _StoryRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoryRating");
                OnStoryRatingChanged();
            }
        }
        private Nullable<global::System.Decimal> _StoryRating;
        partial void OnStoryRatingChanging(Nullable<global::System.Decimal> value);
        partial void OnStoryRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberOfRatings
        {
            get
            {
                return _NumberOfRatings;
            }
            set
            {
                OnNumberOfRatingsChanging(value);
                ReportPropertyChanging("NumberOfRatings");
                _NumberOfRatings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfRatings");
                OnNumberOfRatingsChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberOfRatings;
        partial void OnNumberOfRatingsChanging(Nullable<global::System.Int32> value);
        partial void OnNumberOfRatingsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoriesEntityModel", Name="V2StoryTagSummary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V2StoryTagSummary : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V2StoryTagSummary object.
        /// </summary>
        /// <param name="storyID">Initial value of the StoryID property.</param>
        public static V2StoryTagSummary CreateV2StoryTagSummary(global::System.Decimal storyID)
        {
            V2StoryTagSummary v2StoryTagSummary = new V2StoryTagSummary();
            v2StoryTagSummary.StoryID = storyID;
            return v2StoryTagSummary;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal StoryID
        {
            get
            {
                return _StoryID;
            }
            set
            {
                if (_StoryID != value)
                {
                    OnStoryIDChanging(value);
                    ReportPropertyChanging("StoryID");
                    _StoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StoryID");
                    OnStoryIDChanged();
                }
            }
        }
        private global::System.Decimal _StoryID;
        partial void OnStoryIDChanging(global::System.Decimal value);
        partial void OnStoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionSummary
        {
            get
            {
                return _DescriptionSummary;
            }
            set
            {
                OnDescriptionSummaryChanging(value);
                ReportPropertyChanging("DescriptionSummary");
                _DescriptionSummary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionSummary");
                OnDescriptionSummaryChanged();
            }
        }
        private global::System.String _DescriptionSummary;
        partial void OnDescriptionSummaryChanging(global::System.String value);
        partial void OnDescriptionSummaryChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StoriesEntityModel", Name="V2StoryWithImageAuthor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class V2StoryWithImageAuthor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new V2StoryWithImageAuthor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="storyContent">Initial value of the StoryContent property.</param>
        /// <param name="authorID">Initial value of the AuthorID property.</param>
        /// <param name="imageID">Initial value of the ImageID property.</param>
        /// <param name="postingDate">Initial value of the PostingDate property.</param>
        /// <param name="storyVersion">Initial value of the StoryVersion property.</param>
        /// <param name="editorID">Initial value of the EditorID property.</param>
        /// <param name="reviewApproval">Initial value of the ReviewApproval property.</param>
        /// <param name="finalApproval">Initial value of the FinalApproval property.</param>
        /// <param name="reviewUnsure">Initial value of the ReviewUnsure property.</param>
        /// <param name="isUnusableNegative">Initial value of the IsUnusableNegative property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="owner">Initial value of the Owner property.</param>
        /// <param name="poster">Initial value of the Poster property.</param>
        /// <param name="width">Initial value of the Width property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="mdWidth">Initial value of the MdWidth property.</param>
        /// <param name="mdHeight">Initial value of the MdHeight property.</param>
        /// <param name="lgWidth">Initial value of the LgWidth property.</param>
        /// <param name="lgHeight">Initial value of the LgHeight property.</param>
        /// <param name="promoWidth">Initial value of the PromoWidth property.</param>
        /// <param name="promoHeight">Initial value of the PromoHeight property.</param>
        public static V2StoryWithImageAuthor CreateV2StoryWithImageAuthor(global::System.Decimal id, global::System.String title, global::System.String storyContent, global::System.Decimal authorID, global::System.Decimal imageID, global::System.DateTime postingDate, global::System.Int32 storyVersion, global::System.Int32 editorID, global::System.Boolean reviewApproval, global::System.Boolean finalApproval, global::System.Boolean reviewUnsure, global::System.Boolean isUnusableNegative, global::System.String fileName, global::System.String owner, global::System.Decimal poster, global::System.Decimal width, global::System.Decimal height, global::System.Decimal mdWidth, global::System.Decimal mdHeight, global::System.Decimal lgWidth, global::System.Decimal lgHeight, global::System.Decimal promoWidth, global::System.Decimal promoHeight)
        {
            V2StoryWithImageAuthor v2StoryWithImageAuthor = new V2StoryWithImageAuthor();
            v2StoryWithImageAuthor.ID = id;
            v2StoryWithImageAuthor.Title = title;
            v2StoryWithImageAuthor.StoryContent = storyContent;
            v2StoryWithImageAuthor.AuthorID = authorID;
            v2StoryWithImageAuthor.ImageID = imageID;
            v2StoryWithImageAuthor.PostingDate = postingDate;
            v2StoryWithImageAuthor.StoryVersion = storyVersion;
            v2StoryWithImageAuthor.EditorID = editorID;
            v2StoryWithImageAuthor.ReviewApproval = reviewApproval;
            v2StoryWithImageAuthor.FinalApproval = finalApproval;
            v2StoryWithImageAuthor.ReviewUnsure = reviewUnsure;
            v2StoryWithImageAuthor.IsUnusableNegative = isUnusableNegative;
            v2StoryWithImageAuthor.FileName = fileName;
            v2StoryWithImageAuthor.Owner = owner;
            v2StoryWithImageAuthor.Poster = poster;
            v2StoryWithImageAuthor.Width = width;
            v2StoryWithImageAuthor.Height = height;
            v2StoryWithImageAuthor.MdWidth = mdWidth;
            v2StoryWithImageAuthor.MdHeight = mdHeight;
            v2StoryWithImageAuthor.LgWidth = lgWidth;
            v2StoryWithImageAuthor.LgHeight = lgHeight;
            v2StoryWithImageAuthor.PromoWidth = promoWidth;
            v2StoryWithImageAuthor.PromoHeight = promoHeight;
            return v2StoryWithImageAuthor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoryContent
        {
            get
            {
                return _StoryContent;
            }
            set
            {
                OnStoryContentChanging(value);
                ReportPropertyChanging("StoryContent");
                _StoryContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoryContent");
                OnStoryContentChanged();
            }
        }
        private global::System.String _StoryContent;
        partial void OnStoryContentChanging(global::System.String value);
        partial void OnStoryContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AuthorID
        {
            get
            {
                return _AuthorID;
            }
            set
            {
                OnAuthorIDChanging(value);
                ReportPropertyChanging("AuthorID");
                _AuthorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorID");
                OnAuthorIDChanged();
            }
        }
        private global::System.Decimal _AuthorID;
        partial void OnAuthorIDChanging(global::System.Decimal value);
        partial void OnAuthorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ImageID
        {
            get
            {
                return _ImageID;
            }
            set
            {
                OnImageIDChanging(value);
                ReportPropertyChanging("ImageID");
                _ImageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageID");
                OnImageIDChanged();
            }
        }
        private global::System.Decimal _ImageID;
        partial void OnImageIDChanging(global::System.Decimal value);
        partial void OnImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostingDate
        {
            get
            {
                return _PostingDate;
            }
            set
            {
                OnPostingDateChanging(value);
                ReportPropertyChanging("PostingDate");
                _PostingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostingDate");
                OnPostingDateChanged();
            }
        }
        private global::System.DateTime _PostingDate;
        partial void OnPostingDateChanging(global::System.DateTime value);
        partial void OnPostingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentEntryID
        {
            get
            {
                return _CurrentEntryID;
            }
            set
            {
                OnCurrentEntryIDChanging(value);
                ReportPropertyChanging("CurrentEntryID");
                _CurrentEntryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentEntryID");
                OnCurrentEntryIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentEntryID;
        partial void OnCurrentEntryIDChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentEntryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoryVersion
        {
            get
            {
                return _StoryVersion;
            }
            set
            {
                OnStoryVersionChanging(value);
                ReportPropertyChanging("StoryVersion");
                _StoryVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoryVersion");
                OnStoryVersionChanged();
            }
        }
        private global::System.Int32 _StoryVersion;
        partial void OnStoryVersionChanging(global::System.Int32 value);
        partial void OnStoryVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EditorID
        {
            get
            {
                return _EditorID;
            }
            set
            {
                OnEditorIDChanging(value);
                ReportPropertyChanging("EditorID");
                _EditorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditorID");
                OnEditorIDChanged();
            }
        }
        private global::System.Int32 _EditorID;
        partial void OnEditorIDChanging(global::System.Int32 value);
        partial void OnEditorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ReviewApproval
        {
            get
            {
                return _ReviewApproval;
            }
            set
            {
                OnReviewApprovalChanging(value);
                ReportPropertyChanging("ReviewApproval");
                _ReviewApproval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReviewApproval");
                OnReviewApprovalChanged();
            }
        }
        private global::System.Boolean _ReviewApproval;
        partial void OnReviewApprovalChanging(global::System.Boolean value);
        partial void OnReviewApprovalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean FinalApproval
        {
            get
            {
                return _FinalApproval;
            }
            set
            {
                OnFinalApprovalChanging(value);
                ReportPropertyChanging("FinalApproval");
                _FinalApproval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalApproval");
                OnFinalApprovalChanged();
            }
        }
        private global::System.Boolean _FinalApproval;
        partial void OnFinalApprovalChanging(global::System.Boolean value);
        partial void OnFinalApprovalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Reviewed
        {
            get
            {
                return _Reviewed;
            }
            set
            {
                OnReviewedChanging(value);
                ReportPropertyChanging("Reviewed");
                _Reviewed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Reviewed");
                OnReviewedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Reviewed;
        partial void OnReviewedChanging(Nullable<global::System.Boolean> value);
        partial void OnReviewedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Views
        {
            get
            {
                return _Views;
            }
            set
            {
                OnViewsChanging(value);
                ReportPropertyChanging("Views");
                _Views = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Views");
                OnViewsChanged();
            }
        }
        private Nullable<global::System.Decimal> _Views;
        partial void OnViewsChanging(Nullable<global::System.Decimal> value);
        partial void OnViewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CategoryID;
        partial void OnCategoryIDChanging(Nullable<global::System.Decimal> value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDraft
        {
            get
            {
                return _IsDraft;
            }
            set
            {
                OnIsDraftChanging(value);
                ReportPropertyChanging("IsDraft");
                _IsDraft = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDraft");
                OnIsDraftChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDraft;
        partial void OnIsDraftChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDraftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsUnusable
        {
            get
            {
                return _IsUnusable;
            }
            set
            {
                OnIsUnusableChanging(value);
                ReportPropertyChanging("IsUnusable");
                _IsUnusable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUnusable");
                OnIsUnusableChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsUnusable;
        partial void OnIsUnusableChanging(Nullable<global::System.Boolean> value);
        partial void OnIsUnusableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ReviewUnsure
        {
            get
            {
                return _ReviewUnsure;
            }
            set
            {
                OnReviewUnsureChanging(value);
                ReportPropertyChanging("ReviewUnsure");
                _ReviewUnsure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReviewUnsure");
                OnReviewUnsureChanged();
            }
        }
        private global::System.Boolean _ReviewUnsure;
        partial void OnReviewUnsureChanging(global::System.Boolean value);
        partial void OnReviewUnsureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUnusableNegative
        {
            get
            {
                return _IsUnusableNegative;
            }
            set
            {
                OnIsUnusableNegativeChanging(value);
                ReportPropertyChanging("IsUnusableNegative");
                _IsUnusableNegative = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUnusableNegative");
                OnIsUnusableNegativeChanged();
            }
        }
        private global::System.Boolean _IsUnusableNegative;
        partial void OnIsUnusableNegativeChanging(global::System.Boolean value);
        partial void OnIsUnusableNegativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.String _Owner;
        partial void OnOwnerChanging(global::System.String value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Poster
        {
            get
            {
                return _Poster;
            }
            set
            {
                OnPosterChanging(value);
                ReportPropertyChanging("Poster");
                _Poster = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Poster");
                OnPosterChanged();
            }
        }
        private global::System.Decimal _Poster;
        partial void OnPosterChanging(global::System.Decimal value);
        partial void OnPosterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Decimal _Width;
        partial void OnWidthChanging(global::System.Decimal value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Decimal _Height;
        partial void OnHeightChanging(global::System.Decimal value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MdWidth
        {
            get
            {
                return _MdWidth;
            }
            set
            {
                OnMdWidthChanging(value);
                ReportPropertyChanging("MdWidth");
                _MdWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MdWidth");
                OnMdWidthChanged();
            }
        }
        private global::System.Decimal _MdWidth;
        partial void OnMdWidthChanging(global::System.Decimal value);
        partial void OnMdWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MdHeight
        {
            get
            {
                return _MdHeight;
            }
            set
            {
                OnMdHeightChanging(value);
                ReportPropertyChanging("MdHeight");
                _MdHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MdHeight");
                OnMdHeightChanged();
            }
        }
        private global::System.Decimal _MdHeight;
        partial void OnMdHeightChanging(global::System.Decimal value);
        partial void OnMdHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LgWidth
        {
            get
            {
                return _LgWidth;
            }
            set
            {
                OnLgWidthChanging(value);
                ReportPropertyChanging("LgWidth");
                _LgWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LgWidth");
                OnLgWidthChanged();
            }
        }
        private global::System.Decimal _LgWidth;
        partial void OnLgWidthChanging(global::System.Decimal value);
        partial void OnLgWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LgHeight
        {
            get
            {
                return _LgHeight;
            }
            set
            {
                OnLgHeightChanging(value);
                ReportPropertyChanging("LgHeight");
                _LgHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LgHeight");
                OnLgHeightChanged();
            }
        }
        private global::System.Decimal _LgHeight;
        partial void OnLgHeightChanging(global::System.Decimal value);
        partial void OnLgHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromoWidth
        {
            get
            {
                return _PromoWidth;
            }
            set
            {
                OnPromoWidthChanging(value);
                ReportPropertyChanging("PromoWidth");
                _PromoWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromoWidth");
                OnPromoWidthChanged();
            }
        }
        private global::System.Decimal _PromoWidth;
        partial void OnPromoWidthChanging(global::System.Decimal value);
        partial void OnPromoWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PromoHeight
        {
            get
            {
                return _PromoHeight;
            }
            set
            {
                OnPromoHeightChanging(value);
                ReportPropertyChanging("PromoHeight");
                _PromoHeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromoHeight");
                OnPromoHeightChanged();
            }
        }
        private global::System.Decimal _PromoHeight;
        partial void OnPromoHeightChanging(global::System.Decimal value);
        partial void OnPromoHeightChanged();

        #endregion
    
    }

    #endregion
    
}
