//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfacome.entity.dao.Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Variation
    {
        public int variation_id { get; set; }
        public int parent_food_id { get; set; }
        public int child_food_id { get; set; }
        public bool is_option { get; set; }
        public string hint { get; set; }
    }
}
