// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class food_media : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(food_media));
        
        string IMigrationMetadata.Id
        {
            get { return "201306031631330_food_media"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
