// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class original_capacity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(original_capacity));
        
        string IMigrationMetadata.Id
        {
            get { return "201308021626284_original_capacity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
