// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class group_size : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(group_size));
        
        string IMigrationMetadata.Id
        {
            get { return "201306291753329_group_size"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
