// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class offsiteoccurrence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(offsiteoccurrence));
        
        string IMigrationMetadata.Id
        {
            get { return "201306181525366_offsite-occurrence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
