// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class guest_binding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guest_binding));
        
        string IMigrationMetadata.Id
        {
            get { return "201306302055033_guest_binding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
