// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class menu_keys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(menu_keys));
        
        string IMigrationMetadata.Id
        {
            get { return "201306042027184_menu_keys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
