// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class notes_etc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notes_etc));
        
        string IMigrationMetadata.Id
        {
            get { return "201305241411586_notes_etc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
