// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class food_allowance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(food_allowance));
        
        string IMigrationMetadata.Id
        {
            get { return "201305301615175_food_allowance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
