// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ticketno3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketno3));
        
        string IMigrationMetadata.Id
        {
            get { return "201305090029225_ticket-no3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
