// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class may17merge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(may17merge));
        
        string IMigrationMetadata.Id
        {
            get { return "201305171931041_may17merge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
