// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removing_min_occurrence_capacity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removing_min_occurrence_capacity));
        
        string IMigrationMetadata.Id
        {
            get { return "201308012132034_removing_min_occurrence_capacity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
