// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mediacreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mediacreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201305082012158_media-create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
