//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfatours.entity.dbcontext.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slots_Test
    {
        public int SlotId { get; set; }
        public int Status { get; set; }
        public int Capacity { get; set; }
        public int Visibility { get; set; }
        public System.DateTimeOffset Start { get; set; }
        public Nullable<int> StartDay { get; set; }
        public string NameString { get; set; }
    }
}
