//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfatours.entity.dbcontext.Views
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CfatoursViewContext : DbContext
    {
        public CfatoursViewContext()
            : base("name=CfatoursViewContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Slots_Test> Slots_Test { get; set; }
        public DbSet<TourSlot_Summary> TourSlot_Summary { get; set; }
    }
}
