

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData V3                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

  $data.Entity.extend('StoriesEntityModel.V2StoryImageAuthorWithTagRating', {
    'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Title': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'StoryContent': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':Number.POSITIVE_INFINITY },
    'AuthorID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'ImageID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PostingDate': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'CurrentEntryID': { 'type':'Edm.Decimal' },
    'StoryVersion': { 'type':'Edm.Int32','nullable':false,'required':true },
    'EditorID': { 'type':'Edm.Int32','nullable':false,'required':true },
    'ReviewApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FinalApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'Reviewed': { 'type':'Edm.Boolean' },
    'Views': { 'type':'Edm.Decimal' },
    'CategoryID': { 'type':'Edm.Decimal' },
    'IsDraft': { 'type':'Edm.Boolean' },
    'IsUnusable': { 'type':'Edm.Boolean' },
    'Comment': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'ReviewUnsure': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsUnusableNegative': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FileName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Owner': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'Poster': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Width': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Height': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'StoryRating': { 'type':'Edm.Decimal' },
    'NumberOfRatings': { 'type':'Edm.Int32' },
    'TagDescription': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'Quality': { 'type':'Edm.Int32' },
    'IsFavorite': { 'type':'Edm.Int32' },
    'NewID': { 'type':'Edm.Guid' }
  });
  
  $data.Entity.extend('StoriesEntityModel.V2StoryRatingSummary', {
    'StoryID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'StoryRating': { 'type':'Edm.Decimal' },
    'NumberOfRatings': { 'type':'Edm.Int32' }
  });
  
  $data.Entity.extend('StoriesEntityModel.V2StoryTagSummary', {
    'StoryID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'DescriptionSummary': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'IsFavorite': { 'type':'Edm.Int32' }
  });
  
  $data.Entity.extend('StoriesEntityModel.V2StoryWithImageAuthor', {
    'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Title': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'StoryContent': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':Number.POSITIVE_INFINITY },
    'AuthorID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'ImageID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PostingDate': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'CurrentEntryID': { 'type':'Edm.Decimal' },
    'StoryVersion': { 'type':'Edm.Int32','nullable':false,'required':true },
    'EditorID': { 'type':'Edm.Int32','nullable':false,'required':true },
    'ReviewApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FinalApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'Reviewed': { 'type':'Edm.Boolean' },
    'Views': { 'type':'Edm.Decimal' },
    'CategoryID': { 'type':'Edm.Decimal' },
    'IsDraft': { 'type':'Edm.Boolean' },
    'IsUnusable': { 'type':'Edm.Boolean' },
    'Comment': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'ReviewUnsure': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsUnusableNegative': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FileName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Owner': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'Poster': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Width': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Height': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoHeight': { 'type':'Edm.Decimal','nullable':false,'required':true }
  });
  
  $data.Entity.extend('StoriesEntityModel.V2StoryWithImageAuthorQuality', {
    'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Title': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'StoryContent': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':Number.POSITIVE_INFINITY },
    'AuthorID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'ImageID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PostingDate': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'CurrentEntryID': { 'type':'Edm.Decimal' },
    'StoryVersion': { 'type':'Edm.Int32','nullable':false,'required':true },
    'EditorID': { 'type':'Edm.Int32','nullable':false,'required':true },
    'ReviewApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FinalApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'Reviewed': { 'type':'Edm.Boolean' },
    'Views': { 'type':'Edm.Decimal' },
    'CategoryID': { 'type':'Edm.Decimal' },
    'IsDraft': { 'type':'Edm.Boolean' },
    'IsUnusable': { 'type':'Edm.Boolean' },
    'Comment': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'ReviewUnsure': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsUnusableNegative': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FileName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Owner': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'Poster': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Width': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Height': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Quality': { 'type':'Edm.Int32' },
    'IsFavorite': { 'type':'Edm.Int32','nullable':false,'required':true },
    'StoryRating': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'NewID': { 'type':'Edm.Guid' }
  });
  
  $data.Entity.extend('StoriesEntityModel.V2StoryWithImageAuthorQualityTags', {
    'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Title': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'StoryContent': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':Number.POSITIVE_INFINITY },
    'AuthorID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'ImageID': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PostingDate': { 'type':'Edm.DateTime','nullable':false,'required':true },
    'CurrentEntryID': { 'type':'Edm.Decimal' },
    'StoryVersion': { 'type':'Edm.Int32','nullable':false,'required':true },
    'EditorID': { 'type':'Edm.Int32','nullable':false,'required':true },
    'ReviewApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FinalApproval': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'Reviewed': { 'type':'Edm.Boolean' },
    'Views': { 'type':'Edm.Decimal' },
    'CategoryID': { 'type':'Edm.Decimal' },
    'IsDraft': { 'type':'Edm.Boolean' },
    'IsUnusable': { 'type':'Edm.Boolean' },
    'Comment': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'ReviewUnsure': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsUnusableNegative': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'FileName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Owner': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'Poster': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Width': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'Height': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'MdHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'LgHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoWidth': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoHeight': { 'type':'Edm.Decimal','nullable':false,'required':true },
    'TagID': { 'type':'Edm.Decimal' },
    'IsFavorite': { 'type':'Edm.Int32' },
    'Quality': { 'type':'Edm.Int32' },
    'GroupID': { 'type':'Edm.Int32' },
    'TagDescription': { 'type':'Edm.String','maxLength':50 },
    'NewID': { 'type':'Edm.Guid' }
  });
  
  $data.Entity.extend('StoriesEntityModel.StoryLocation', {
    'StoryID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'StoreID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'CreationDate': { 'type':'Edm.DateTime','nullable':false,'required':true }
  });
  
  $data.Entity.extend('StoriesEntityModel.StoryLocation_Location', {
    'StoryID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'StoreID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'CreationDate': { 'key':true,'type':'Edm.DateTime','nullable':false,'required':true },
    'LocationNumber': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Name': { 'type':'Edm.String','maxLength':100 },
    'MarketableName': { 'type':'Edm.String','maxLength':100 },
    'OperatorContact_PersonID': { 'type':'Edm.Decimal' },
    'OperatorContact_Name': { 'type':'Edm.String','maxLength':100 },
    'StreetAddress_Address1': { 'type':'Edm.String','maxLength':100 },
    'StreetAddress_City': { 'type':'Edm.String','maxLength':100 },
    'StreetAddress_County': { 'type':'Edm.String','maxLength':100 },
    'StreetAddress_State': { 'type':'Edm.String','maxLength':100 },
    'StreetAddress_Zip': { 'type':'Edm.String','maxLength':100 },
    'StreetAddress_ZipExtension': { 'type':'Edm.String','maxLength':100 },
    'ShippingAddress_Address1': { 'type':'Edm.String','maxLength':100 },
    'ShippingAddress_City': { 'type':'Edm.String','maxLength':100 },
    'ShippingAddress_County': { 'type':'Edm.String','maxLength':100 },
    'ShippingAddress_State': { 'type':'Edm.String','maxLength':100 },
    'ShippingAddress_Zip': { 'type':'Edm.String','maxLength':100 },
    'ShippingAddress_ZipExtension': { 'type':'Edm.String','maxLength':100 },
    'BillingAddress_Address1': { 'type':'Edm.String','maxLength':100 },
    'BillingAddress_City': { 'type':'Edm.String','maxLength':100 },
    'BillingAddress_County': { 'type':'Edm.String','maxLength':100 },
    'BillingAddress_State': { 'type':'Edm.String','maxLength':100 },
    'BillingAddress_Zip': { 'type':'Edm.String','maxLength':100 },
    'BillingAddress_ZipExtension': { 'type':'Edm.String','maxLength':100 },
    'AreaCode': { 'type':'Edm.String','maxLength':100 },
    'PhoneNumber': { 'type':'Edm.String','maxLength':100 },
    'EmailAddress': { 'type':'Edm.String','maxLength':100 },
    'VoiceMail': { 'type':'Edm.String','maxLength':100 },
    'Status': { 'type':'Edm.String','maxLength':100 },
    'OpenDate': { 'type':'Edm.DateTime' },
    'ProjectedOpenDate': { 'type':'Edm.DateTime' },
    'MarketableURL': { 'type':'Edm.String','maxLength':500 },
    'GPS_Latitude': { 'type':'Edm.String','maxLength':100 },
    'GPS_Longitude': { 'type':'Edm.String','maxLength':100 },
    'ConceptCode': { 'type':'Edm.String','maxLength':100 },
    'LocationCode': { 'type':'Edm.String','maxLength':100 },
    'Playground': { 'type':'Edm.String','maxLength':100 },
    'OffersOnlineOrdering': { 'type':'Edm.Boolean' },
    'HasDriveThru': { 'type':'Edm.Boolean' },
    'AcceptsCfaCard': { 'type':'Edm.Boolean' },
    'HasDiningRoom': { 'type':'Edm.Boolean' },
    'ServesBreakfast': { 'type':'Edm.Boolean' },
    'OffersWireless': { 'type':'Edm.Boolean' },
    'NoUpdate': { 'type':'Edm.Boolean' },
    'FaxNumber': { 'type':'Edm.String','maxLength':50 },
    'FaxAreaCode': { 'type':'Edm.String','maxLength':50 },
    'Message': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'CorporateOwned': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
    'LocationDescription': { 'type':'Edm.String','maxLength':100 }
  });
  
  $data.Entity.extend('StoriesEntityModel.Location_Story', {
    'StoryID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'StoreID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'CreationDate': { 'key':true,'type':'Edm.DateTime','nullable':false,'required':true },
    'ID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Title': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'StoryContent': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':Number.POSITIVE_INFINITY },
    'AuthorID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'ImageID': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'PostingDate': { 'key':true,'type':'Edm.DateTime','nullable':false,'required':true },
    'CurrentEntryID': { 'type':'Edm.Decimal' },
    'StoryVersion': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'EditorID': { 'key':true,'type':'Edm.Int32','nullable':false,'required':true },
    'ReviewApproval': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
    'FinalApproval': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
    'Reviewed': { 'type':'Edm.Boolean' },
    'Views': { 'type':'Edm.Decimal' },
    'CategoryID': { 'type':'Edm.Decimal' },
    'IsDraft': { 'type':'Edm.Boolean' },
    'IsUnusable': { 'type':'Edm.Boolean' },
    'Comment': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'ReviewUnsure': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
    'IsUnusableNegative': { 'key':true,'type':'Edm.Boolean','nullable':false,'required':true },
    'FileName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Owner': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':1 },
    'Poster': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Width': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'Height': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'MdWidth': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'MdHeight': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'LgWidth': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'LgHeight': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoWidth': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'PromoHeight': { 'key':true,'type':'Edm.Decimal','nullable':false,'required':true },
    'StoryRating': { 'type':'Edm.Decimal' },
    'NumberOfRatings': { 'type':'Edm.Int32' },
    'TagDescription': { 'type':'Edm.String','maxLength':Number.POSITIVE_INFINITY },
    'Quality': { 'type':'Edm.Int32' },
    'IsFavorite': { 'type':'Edm.Int32' },
    'NewID': { 'type':'Edm.Guid' }
  });
  
  $data.EntityContext.extend('cfacom.entity.dao.Designer.CfaComStoriesEntities', {
    'V2StoryImageAuthorWithTagRating': { type: $data.EntitySet, elementType: StoriesEntityModel.V2StoryImageAuthorWithTagRating },
    'V2StoryRatingSummary': { type: $data.EntitySet, elementType: StoriesEntityModel.V2StoryRatingSummary },
    'V2StoryTagSummary': { type: $data.EntitySet, elementType: StoriesEntityModel.V2StoryTagSummary },
    'V2StoryWithImageAuthor': { type: $data.EntitySet, elementType: StoriesEntityModel.V2StoryWithImageAuthor },
    'V2StoryWithImageAuthorQuality': { type: $data.EntitySet, elementType: StoriesEntityModel.V2StoryWithImageAuthorQuality },
    'V2StoryWithImageAuthorQualityTags': { type: $data.EntitySet, elementType: StoriesEntityModel.V2StoryWithImageAuthorQualityTags },
    'StoryLocations': { type: $data.EntitySet, elementType: StoriesEntityModel.StoryLocation },
    'StoryLocation_Location': { type: $data.EntitySet, elementType: StoriesEntityModel.StoryLocation_Location },
    'Location_Story': { type: $data.EntitySet, elementType: StoriesEntityModel.Location_Story }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(cfacom.entity.dao.Designer.CfaComStoriesEntities);
  
  /*Context Instance*/
  cfacom.entity.dao.Designer.context = new cfacom.entity.dao.Designer.CfaComStoriesEntities( { name:'oData', oDataServiceHost: 'http://core.chick-fil-a.com/DataServices/Stories.svc' });

      
})(window, $data);
      
    