// <auto-generated />
namespace cfa.admin.context.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class order_social_networks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order_social_networks));
        
        string IMigrationMetadata.Id
        {
            get { return "201304231739018_order_social_networks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
