// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class enum_cleanup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enum_cleanup));
        
        string IMigrationMetadata.Id
        {
            get { return "201304071824442_enum_cleanup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
