// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class template_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(template_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201303291532306_template_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
