// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class storeenahancement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storeenahancement));
        
        string IMigrationMetadata.Id
        {
            get { return "201305071509559_store-enahancement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
