// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResStoreChildcareAvailableParkingNotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResStoreChildcareAvailableParkingNotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201304142248053_ResStoreChildcareAvailableParkingNotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
