// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class timezone_applied_dls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timezone_applied_dls));
        
        string IMigrationMetadata.Id
        {
            get { return "201303270046344_timezone_applied_dls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
