// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class template_preview_foreign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(template_preview_foreign));
        
        string IMigrationMetadata.Id
        {
            get { return "201303220233096_template_preview_foreign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
