// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OccurrenceStoreFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OccurrenceStoreFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201303241757422_OccurrenceStoreFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
