// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class store_region : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_region));
        
        string IMigrationMetadata.Id
        {
            get { return "201302111944120_store_region"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
