// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class store_price_group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_price_group));
        
        string IMigrationMetadata.Id
        {
            get { return "201302111947502_store_price_group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
