// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OccurrenceStores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OccurrenceStores));
        
        string IMigrationMetadata.Id
        {
            get { return "201303242114260_OccurrenceStores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
