// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class occurrence_range1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(occurrence_range1));
        
        string IMigrationMetadata.Id
        {
            get { return "201303291505036_occurrence_range1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
