// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201302082031018_user_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
