// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class storeuserroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(storeuserroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201304191400569_store-user-roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
