// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReservationType_Mig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReservationType_Mig));
        
        string IMigrationMetadata.Id
        {
            get { return "201301312000153_ReservationType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
