// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_unique_keys2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_unique_keys2));
        
        string IMigrationMetadata.Id
        {
            get { return "201304101537513_user_unique_keys2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
