// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class npr_clean : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(npr_clean));
        
        string IMigrationMetadata.Id
        {
            get { return "201305062108047_npr_clean"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
