// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class store_message : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_message));
        
        string IMigrationMetadata.Id
        {
            get { return "201302111717511_store_message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
