// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_address));
        
        string IMigrationMetadata.Id
        {
            get { return "201304082119047_user_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
