// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class timezone_applied_dls2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timezone_applied_dls2));
        
        string IMigrationMetadata.Id
        {
            get { return "201303270113005_timezone_applied_dls2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
