// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class slot_required_dropped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slot_required_dropped));
        
        string IMigrationMetadata.Id
        {
            get { return "201305072314442_slot_required_dropped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
