// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class res_user_cleanup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(res_user_cleanup));
        
        string IMigrationMetadata.Id
        {
            get { return "201304041825162_res_user_cleanup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
