// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _enum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_enum));
        
        string IMigrationMetadata.Id
        {
            get { return "201304051950081_enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
