// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResEvent1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResEvent1));
        
        string IMigrationMetadata.Id
        {
            get { return "201301311943090_ResEvent1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
