// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class no_event_status_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(no_event_status_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201304011739178_no_event_status_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
