// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class occurrence_slot_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(occurrence_slot_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201304021842416_occurrence_slot_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
