// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class store_bidirectional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(store_bidirectional));
        
        string IMigrationMetadata.Id
        {
            get { return "201303221525398_store_bidirectional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
