// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class media_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(media_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201303201914520_media_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
