// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class no_total_tickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(no_total_tickets));
        
        string IMigrationMetadata.Id
        {
            get { return "201304121358520_no_total_tickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
