// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResUserExtensionsMergeLatLon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResUserExtensionsMergeLatLon));
        
        string IMigrationMetadata.Id
        {
            get { return "201304072354414_ResUserExtensionsMergeLatLon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
