// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ResEvent3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ResEvent3));
        
        string IMigrationMetadata.Id
        {
            get { return "201301312016181_ResEvent3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
