// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class occurrence_m2m : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(occurrence_m2m));
        
        string IMigrationMetadata.Id
        {
            get { return "201303281421063_occurrence_m2m"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
