// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class guide_designation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(guide_designation));
        
        string IMigrationMetadata.Id
        {
            get { return "201304041557079_guide_designation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
