// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class media_external_primary2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(media_external_primary2));
        
        string IMigrationMetadata.Id
        {
            get { return "201303211836129_media_external_primary2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
