// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class wizard_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wizard_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201303201518532_wizard_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
