// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_table1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_table1));
        
        string IMigrationMetadata.Id
        {
            get { return "201302082102081_user_table1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
