// <auto-generated />
namespace cfares.entity.dbcontext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MenuItemM2M : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuItemM2M));
        
        string IMigrationMetadata.Id
        {
            get { return "201302062120247_MenuItemM2M"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
