//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakfastConflictAction
    {
        public int ID { get; set; }
        public string food { get; set; }
        public System.DateTime acted { get; set; }
        public int conflictID { get; set; }
        public string slot { get; set; }
    }
}
