//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class BreakfastConflict
    {
        public int ID { get; set; }
        public string email { get; set; }
        public string eventID { get; set; }
        public string regID { get; set; }
        public Nullable<int> storeID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string fullName { get; set; }
        public int conflict { get; set; }
        public string slotID { get; set; }
        public string foodID { get; set; }
        public Nullable<long> dob { get; set; }
        public string gender { get; set; }
        public bool subscriber { get; set; }
        public bool newuser { get; set; }
        public Nullable<long> barcode { get; set; }
        public bool finished { get; set; }
        public string hash { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string address { get; set; }
        public string zip { get; set; }
        public int emailed { get; set; }
    }
}
