//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Care
    {
        public int ID { get; set; }
        public string SITE_ID { get; set; }
        public string TITLE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string ALT_PHONE_NUMBER { get; set; }
        public string GENDER { get; set; }
        public string AGE { get; set; }
        public bool CONTACTED_OPERATOR { get; set; }
        public string STORE_NUMBER { get; set; }
        public string LOCATION { get; set; }
        public string STORE_ADDRESS { get; set; }
        public string STORE_CITY { get; set; }
        public string STORE_ZIP_CODE { get; set; }
        public System.DateTime DATE_OF_VISIT { get; set; }
        public string MEAL { get; set; }
        public string MEAL_TYPE { get; set; }
        public string COMM_METHOD { get; set; }
        public string COMMENTS { get; set; }
        public string HOW_OFTEN { get; set; }
        public string AGENT_STR { get; set; }
    }
}
