//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CfaComEntities : DbContext
    {
        public CfaComEntities()
            : base("name=CfaComEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlohaLiveDate> AlohaLiveDates { get; set; }
        public DbSet<BreakfastConflict> BreakfastConflicts { get; set; }
        public DbSet<BreakfastConflictAction> BreakfastConflictActions { get; set; }
        public DbSet<Care> Cares { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Event_Location> Event_Location { get; set; }
        public DbSet<EventRegistration> EventRegistrations { get; set; }
        public DbSet<FAQ> FAQs { get; set; }
        public DbSet<FAQs_Group> FAQs_Group { get; set; }
        public DbSet<FavoriteLocation> FavoriteLocations { get; set; }
        public DbSet<Feed> Feeds { get; set; }
        public DbSet<First100Attendees> First100Attendees { get; set; }
        public DbSet<Food> Foods { get; set; }
        public DbSet<Food_Category> Food_Category { get; set; }
        public DbSet<Food_Ingredient> Food_Ingredient { get; set; }
        public DbSet<Food_Variation> Food_Variation { get; set; }
        public DbSet<FoodImage> FoodImages { get; set; }
        public DbSet<Mail> Mails { get; set; }
        public DbSet<Press_Group> Press_Group { get; set; }
        public DbSet<Press_Image> Press_Image { get; set; }
        public DbSet<Press_Release> Press_Release { get; set; }
        public DbSet<Press_Store> Press_Store { get; set; }
        public DbSet<PublishingLog> PublishingLogs { get; set; }
        public DbSet<ResponseTag> ResponseTags { get; set; }
        public DbSet<SiteError> SiteErrors { get; set; }
        public DbSet<SiteStory> SiteStories { get; set; }
        public DbSet<SiteUser> SiteUsers { get; set; }
        public DbSet<StoreInfo> StoreInfoes { get; set; }
        public DbSet<StoryEntry> StoryEntries { get; set; }
        public DbSet<StoryEvent> StoryEvents { get; set; }
        public DbSet<StoryImage> StoryImages { get; set; }
        public DbSet<StoryLocation> StoryLocations { get; set; }
        public DbSet<StoryRating> StoryRatings { get; set; }
        public DbSet<StoryTopic> StoryTopics { get; set; }
        public DbSet<Subscriber> Subscribers { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TagGroup> TagGroups { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<TopicResponse> TopicResponses { get; set; }
        public DbSet<TopicTag> TopicTags { get; set; }
        public DbSet<USState> USStates { get; set; }
    }
}
