//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public decimal ID { get; set; }
        public string Title { get; set; }
        public string dom_id { get; set; }
        public System.DateTime Begins { get; set; }
        public System.DateTime Expires { get; set; }
        public string Body { get; set; }
        public string Brief { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> AuthorID { get; set; }
        public string Venue { get; set; }
    }
}
