//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQs_Group
    {
        public int faq_group_id { get; set; }
        public string group_name { get; set; }
        public string group_url_name { get; set; }
        public bool hidden { get; set; }
        public Nullable<int> cover_story { get; set; }
    }
}
