//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int food_id { get; set; }
        public string short_name { get; set; }
        public string food_name { get; set; }
        public string extended_name { get; set; }
        public string url_name { get; set; }
        public string url_hint { get; set; }
        public int order_hint { get; set; }
        public string img { get; set; }
        public string dom_id { get; set; }
        public string description { get; set; }
        public string ingredients { get; set; }
        public Nullable<int> calories { get; set; }
        public Nullable<int> calories_fat { get; set; }
        public Nullable<double> protein { get; set; }
        public Nullable<double> carbs { get; set; }
        public Nullable<double> carbs_daily { get; set; }
        public Nullable<double> sugar { get; set; }
        public Nullable<double> sugar_daily { get; set; }
        public Nullable<double> cholesterol { get; set; }
        public Nullable<double> cholesterol_daily { get; set; }
        public Nullable<double> sodium { get; set; }
        public Nullable<double> sodium_daily { get; set; }
        public Nullable<double> calcium { get; set; }
        public Nullable<double> calcium_daily { get; set; }
        public Nullable<double> iron { get; set; }
        public Nullable<double> iron_daily { get; set; }
        public Nullable<double> fiber { get; set; }
        public Nullable<double> fiber_daily { get; set; }
        public Nullable<double> fat { get; set; }
        public Nullable<double> fat_daily { get; set; }
        public Nullable<double> trans_fat { get; set; }
        public Nullable<double> trans_fat_daily { get; set; }
        public Nullable<double> saturated_fat { get; set; }
        public Nullable<double> saturated_fat_daily { get; set; }
        public Nullable<double> vitamin_a { get; set; }
        public Nullable<double> vitamin_a_daily { get; set; }
        public Nullable<double> vitamin_c { get; set; }
        public Nullable<double> vitamin_c_daily { get; set; }
        public Nullable<double> serving_size { get; set; }
        public Nullable<double> serving_size_international { get; set; }
        public Nullable<int> parent_item { get; set; }
        public bool non_menu { get; set; }
        public bool no_image { get; set; }
        public string notice { get; set; }
        public bool show_serving { get; set; }
    }
}
