//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodImage
    {
        public int image_id { get; set; }
        public string name { get; set; }
        public string img_url_name { get; set; }
        public string src { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public string brief { get; set; }
        public double ratio { get; set; }
        public int size { get; set; }
        public int food_id { get; set; }
    }
}
