//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Ingredient
    {
        public int food_ingredient_id { get; set; }
        public int food_id { get; set; }
        public int ingredient_id { get; set; }
        public double amount { get; set; }
        public bool optional { get; set; }
    }
}
