//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int ID { get; set; }
        public string FormName { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
