//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Press_Release
    {
        public int release_id { get; set; }
        public string title { get; set; }
        public System.DateTime publish_date { get; set; }
        public string img { get; set; }
        public string body { get; set; }
        public string doc { get; set; }
        public string pdf { get; set; }
        public string brief { get; set; }
        public string url_name { get; set; }
        public int press_group_id { get; set; }
        public string dom_id { get; set; }
    }
}
