//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Press_Group
    {
        public int press_group_id { get; set; }
        public string press_group_name { get; set; }
        public string press_group_url_name { get; set; }
        public int cover_story { get; set; }
        public short date_mode { get; set; }
    }
}
