//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseTag
    {
        public int ID { get; set; }
        public int ResponseID { get; set; }
        public Nullable<int> UserID { get; set; }
        public long IP { get; set; }
        public System.DateTime CreationDate { get; set; }
        public short Score { get; set; }
    }
}
