//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteUser
    {
        public SiteUser()
        {
            this.SiteStories = new HashSet<SiteStory>();
        }
    
        public decimal ID { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string NickName { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string FavoriteStore { get; set; }
        public string TrackingID { get; set; }
        public decimal SecurityQuestionID { get; set; }
        public string SecurityAnswer { get; set; }
        public string Roles { get; set; }
        public string RecoverHash { get; set; }
        public Nullable<System.DateTime> HashCreation { get; set; }
        public string PasswordMode { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Fax { get; set; }
        public bool CanAuthenticate { get; set; }
    
        public virtual ICollection<SiteStory> SiteStories { get; set; }
    }
}
