//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteStory
    {
        public SiteStory()
        {
            this.StoryRatings = new HashSet<StoryRating>();
            this.Tags = new HashSet<Tag>();
        }
    
        public decimal ID { get; set; }
        public string Title { get; set; }
        public string StoryContent { get; set; }
        public decimal AuthorID { get; set; }
        public decimal ImageID { get; set; }
        public System.DateTime PostingDate { get; set; }
        public bool ReviewApproval { get; set; }
        public bool FinalApproval { get; set; }
        public Nullable<bool> Reviewed { get; set; }
        public Nullable<decimal> Views { get; set; }
        public Nullable<decimal> CategoryID { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public Nullable<bool> IsUnusable { get; set; }
        public string Location { get; set; }
        public string Comment { get; set; }
        public bool IsUnusableNegative { get; set; }
        public bool ReviewUnsure { get; set; }
        public Nullable<decimal> CurrentEntryID { get; set; }
    
        public virtual SiteUser SiteUser { get; set; }
        public virtual ICollection<StoryRating> StoryRatings { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
