//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteError
    {
        public int site_error_id { get; set; }
        public int error_code { get; set; }
        public System.DateTime creation_date { get; set; }
        public string message { get; set; }
        public string context_data { get; set; }
        public string callstack { get; set; }
    }
}
