//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryImage
    {
        public decimal ID { get; set; }
        public string FileName { get; set; }
        public string Owner { get; set; }
        public decimal Poster { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal LgWidth { get; set; }
        public decimal LgHeight { get; set; }
        public decimal MdWidth { get; set; }
        public decimal MdHeight { get; set; }
        public decimal PromoHeight { get; set; }
        public decimal PromoWidth { get; set; }
    }
}
