//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInfo
    {
        public string LocationNumber { get; set; }
        public string Name { get; set; }
        public string MarketableName { get; set; }
        public Nullable<decimal> OperatorContact_PersonID { get; set; }
        public string OperatorContact_Name { get; set; }
        public string StreetAddress_Address1 { get; set; }
        public string StreetAddress_City { get; set; }
        public string StreetAddress_County { get; set; }
        public string StreetAddress_State { get; set; }
        public string StreetAddress_Zip { get; set; }
        public string StreetAddress_ZipExtension { get; set; }
        public string ShippingAddress_Address1 { get; set; }
        public string ShippingAddress_City { get; set; }
        public string ShippingAddress_County { get; set; }
        public string ShippingAddress_State { get; set; }
        public string ShippingAddress_Zip { get; set; }
        public string ShippingAddress_ZipExtension { get; set; }
        public string BillingAddress_Address1 { get; set; }
        public string BillingAddress_City { get; set; }
        public string BillingAddress_County { get; set; }
        public string BillingAddress_State { get; set; }
        public string BillingAddress_Zip { get; set; }
        public string BillingAddress_ZipExtension { get; set; }
        public string AreaCode { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string VoiceMail { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> ProjectedOpenDate { get; set; }
        public string MarketableURL { get; set; }
        public string GPS_Latitude { get; set; }
        public string GPS_Longitude { get; set; }
        public string ConceptCode { get; set; }
        public string LocationCode { get; set; }
        public string Playground { get; set; }
        public Nullable<bool> OffersOnlineOrdering { get; set; }
        public Nullable<bool> HasDriveThru { get; set; }
        public Nullable<bool> AcceptsCfaCard { get; set; }
        public Nullable<bool> HasDiningRoom { get; set; }
        public Nullable<bool> ServesBreakfast { get; set; }
        public Nullable<bool> OffersWireless { get; set; }
        public Nullable<bool> NoUpdate { get; set; }
        public string FaxNumber { get; set; }
        public string FaxAreaCode { get; set; }
        public string Message { get; set; }
        public bool CorporateOwned { get; set; }
        public string LocationDescription { get; set; }
    }
}
