//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryRating
    {
        public decimal StoryID { get; set; }
        public string UserTrackingID { get; set; }
        public decimal Rating { get; set; }
        public System.DateTime RatingDate { get; set; }
    
        public virtual SiteStory SiteStory { get; set; }
    }
}
