//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public decimal ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string GENDER { get; set; }
        public string OPT_IN_FLAG { get; set; }
        public Nullable<System.DateTime> OPT_IN_DATE { get; set; }
        public Nullable<System.DateTime> OPT_OUT_DATE { get; set; }
        public Nullable<bool> KIDS_AND_FAMILY_NEWSLETTER { get; set; }
    }
}
