//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicResponse
    {
        public int ID { get; set; }
        public int TopicID { get; set; }
        public int AuthorID { get; set; }
        public string Body { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Info { get; set; }
        public string dom_id { get; set; }
        public long Tags { get; set; }
        public short Visibility { get; set; }
        public string Brief { get; set; }
        public string Title { get; set; }
        public string Attachment { get; set; }
        public string Img { get; set; }
        public short order_hint { get; set; }
        public string Uri { get; set; }
        public int Score { get; set; }
    }
}
