//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfares.routine.full.ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class USState
    {
        public int state_id { get; set; }
        public string state_short { get; set; }
        public string state_long { get; set; }
        public string boundaries { get; set; }
        public string relative_boundaries { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public string img { get; set; }
        public string img_roll { get; set; }
        public double px { get; set; }
        public double py { get; set; }
        public double width { get; set; }
        public double height { get; set; }
        public int parent_id { get; set; }
        public bool contiguous { get; set; }
    }
}
